name: CI

on:
  pull_request:
    branches: 
        - main

permissions:
  contents: read      
  packages: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests ruff

      - name: Check for bugs and style errors
        uses: astral-sh/ruff-action@v3
        with:
          src: "."

      - name: Check for bad formatting
        uses: astral-sh/ruff-action@v3
        with:
          src: "."
          args: "format --check"
        